"""
Site Manifesto Contract
=======================

Pydantic models for the Discovery Agent's output.
The Site Manifesto is a structured JSON map of the Application Under Test (AUT),
including pages, interactive elements, locators, and accessibility metadata.
"""

from enum import Enum

from pydantic import BaseModel, Field


class LocatorStrategy(str, Enum):
    """Supported locator strategies for UI elements."""

    DATA_TESTID = "data-testid"
    ROLE = "role"
    TEXT = "text"
    LABEL = "label"
    PLACEHOLDER = "placeholder"
    ALT_TEXT = "alt-text"
    TITLE = "title"
    NAME = "name"


class UIComponent(BaseModel):
    """A single interactive UI component on a page."""

    tag: str = Field(description="HTML tag name (e.g., 'button', 'input', 'a')")
    text: str = Field(default="", description="Visible text content of the element")
    component_type: str = Field(default="", description="Semantic type (e.g., 'navigation', 'form', 'action')")
    locator_strategy: LocatorStrategy = Field(default=LocatorStrategy.TEXT, description="Recommended locator strategy")
    locator_value: str = Field(default="", description="The value to use with the locator strategy")
    aria_role: str = Field(default="", description="WAI-ARIA role attribute")
    aria_label: str = Field(default="", description="WAI-ARIA label attribute")
    element_id: str = Field(default="", description="HTML id attribute")
    element_name: str = Field(default="", description="HTML name attribute")
    href: str = Field(default="", description="Link target URL (for anchors)")
    input_type: str = Field(default="", description="Input type attribute (for inputs)")
    is_high_risk: bool = Field(default=False, description="Flagged as dangerous (e.g., Delete, Purge)")
    data_testid: str = Field(default="", description="data-testid attribute value")


class PageEntry(BaseModel):
    """A single page in the AUT with its components."""

    url: str = Field(description="Full URL of the page")
    path: str = Field(default="", description="URL path component (e.g., '/login')")
    title: str = Field(default="", description="Page title from <title> tag")
    description: str = Field(default="", description="Meta description or page summary")
    requires_auth: bool = Field(default=False, description="Whether this page requires authentication")
    components: list[UIComponent] = Field(default_factory=list, description="Interactive UI components on this page")
    links: list[str] = Field(default_factory=list, description="Outbound links found on this page")
    forms: int = Field(default=0, description="Number of forms on the page")
    accessibility_tree_hash: str = Field(default="", description="Hash of the accessibility tree for change detection")


class SiteManifesto(BaseModel):
    """Complete map of the Application Under Test.

    Generated by the Discovery Agent after crawling the AUT.
    Used by the Engineer Agent for Look-Before-You-Leap verification.
    """

    aut_base_url: str = Field(description="Base URL of the Application Under Test")
    aut_name: str = Field(default="", description="Name of the application")
    crawl_timestamp: str = Field(default="", description="ISO 8601 timestamp of the crawl")
    total_pages: int = Field(default=0, description="Total number of pages discovered")
    total_components: int = Field(default=0, description="Total interactive components across all pages")
    pages: list[PageEntry] = Field(default_factory=list, description="All discovered pages")
    auth_required: bool = Field(default=False, description="Whether the AUT requires authentication")
    auth_url: str = Field(default="", description="URL of the login/auth page")
    high_risk_actions: list[str] = Field(
        default_factory=list, description="List of high-risk actions flagged for manual review"
    )
