"""
Playwright CLI Tools
===================

Tools for interacting with Playwright CLI to run Playwright Test Agents (planner, generator, healer).
"""

import os
import subprocess
from pathlib import Path
from typing import Optional

from agno.tools import tool

# Configuration
AUTOMATION_DIR = Path(__file__).parent.parent.parent / "automation"
TECHNICAL_TESTS_DIR = AUTOMATION_DIR / "technical-tests"


@tool
def init_playwright_agents() -> str:
    """Initialize Playwright Test Agents in the automation directory.

    This runs `npx playwright init-agents --loop=vscode` to generate
    the agent definitions for planner, generator, and healer.

    Returns:
        str: Success message or error details
    """
    try:
        result = subprocess.run(
            ["npx", "playwright", "init-agents", "--loop=vscode"],
            cwd=AUTOMATION_DIR,
            capture_output=True,
            text=True,
            timeout=120,
        )
        
        if result.returncode == 0:
            return "Playwright Test Agents initialized successfully. Agent definitions generated in .github/agents/"
        else:
            return f"Error initializing Playwright Test Agents: {result.stderr}"
    except subprocess.TimeoutExpired:
        return "Error: Playwright init-agents command timed out"
    except Exception as e:
        return f"Error initializing Playwright Test Agents: {str(e)}"


@tool
def run_planner(url: str, requirements: str, seed_test: str = "seed.spec.ts") -> str:
    """Run the Playwright planner agent to generate a Markdown test plan.

    Args:
        url (str): The AUT URL to explore
        requirements (str): Test requirements and scenarios to plan
        seed_test (str): Path to seed test file (default: seed.spec.ts)

    Returns:
        str: Generated Markdown test plan or error details
    """
    try:
        # Create specs directory if it doesn't exist
        specs_dir = TECHNICAL_TESTS_DIR / "specs"
        specs_dir.mkdir(parents=True, exist_ok=True)
        
        # Note: This is a simplified version. In production, you would interact
        # with the planner agent through its MCP interface or prompt the LLM
        # to use the planner agent definitions.
        
        # For now, we'll create a placeholder that indicates the planner would run
        plan_content = f"""# Test Plan for {url}

## Requirements
{requirements}

## Test Scenarios
To be generated by Playwright planner agent.

## Seed Test
{seed_test}

Note: This is a placeholder. The actual planner agent would be invoked
through its agent definitions in .github/agents/.
"""
        
        plan_file = specs_dir / "test-plan.md"
        plan_file.write_text(plan_content)
        
        return f"Planner agent would generate test plan. Placeholder created at {plan_file}"
    except Exception as e:
        return f"Error running planner: {str(e)}"


@tool
def run_generator(plan_file: str) -> str:
    """Run the Playwright generator agent to create Playwright tests from Markdown plan.

    Args:
        plan_file (str): Path to the Markdown test plan file

    Returns:
        str: Generated test file paths or error details
    """
    try:
        # Create tests directory if it doesn't exist
        tests_dir = TECHNICAL_TESTS_DIR / "tests"
        tests_dir.mkdir(parents=True, exist_ok=True)
        
        # Note: This is a simplified version. In production, you would interact
        # with the generator agent through its MCP interface.
        
        # For now, we'll create a placeholder test file
        test_content = f"""// Generated from: {plan_file}
// Note: This is a placeholder. The actual generator agent would be invoked
// through its agent definitions in .github/agents/.

import {{ test, expect }} from '@playwright/test';

test.describe('Placeholder Test', () => {{
  test('example test', async ({{ page }}) => {{
    await page.goto('https://example.com');
    await expect(page).toHaveTitle(/Example/);
  }});
}});
"""
        
        test_file = tests_dir / "placeholder.spec.ts"
        test_file.write_text(test_content)
        
        return f"Generator agent would create Playwright tests. Placeholder created at {test_file}"
    except Exception as e:
        return f"Error running generator: {str(e)}"


@tool
def run_healer(test_file: str) -> str:
    """Run the Playwright healer agent to repair failing tests.

    Args:
        test_file (str): Path to the failing test file

    Returns:
        str: Healing results or error details
    """
    try:
        # Note: This is a simplified version. In production, you would interact
        # with the healer agent through its MCP interface.
        
        # For now, we'll indicate that the healer would run
        return f"Healer agent would repair test: {test_file}. The healer replays the failing steps, inspects the UI, suggests patches, and re-runs until passing."
    except Exception as e:
        return f"Error running healer: {str(e)}"


@tool
def list_generated_tests() -> str:
    """List all generated Playwright tests in the technical-tests directory.

    Returns:
        str: List of test files or message if none exist
    """
    try:
        tests_dir = TECHNICAL_TESTS_DIR / "tests"
        
        if not tests_dir.exists():
            return "No tests directory found. Run generator first."
        
        test_files = list(tests_dir.glob("*.spec.ts"))
        
        if not test_files:
            return "No test files found in technical-tests/tests/"
        
        result = "Generated tests:\n"
        for test_file in sorted(test_files):
            result += f"  - {test_file.name}\n"
        
        return result
    except Exception as e:
        return f"Error listing tests: {str(e)}"


@tool
def run_tests(test_file: Optional[str] = None) -> str:
    """Run generated Playwright tests.

    Args:
        test_file (str): Optional specific test file to run. If not provided, runs all tests.

    Returns:
        str: Test execution results
    """
    try:
        tests_dir = TECHNICAL_TESTS_DIR / "tests"
        
        if test_file:
            test_path = tests_dir / test_file
            if not test_path.exists():
                return f"Test file not found: {test_file}"
            cmd = ["npx", "playwright", "test", str(test_path)]
        else:
            if not tests_dir.exists():
                return "No tests directory found. Run generator first."
            cmd = ["npx", "playwright", "test", str(tests_dir)]
        
        result = subprocess.run(
            cmd,
            cwd=AUTOMATION_DIR,
            capture_output=True,
            text=True,
            timeout=300,
        )
        
        if result.returncode == 0:
            return f"Tests passed:\n{result.stdout}"
        else:
            return f"Tests failed:\n{result.stderr}"
    except subprocess.TimeoutExpired:
        return "Error: Test execution timed out"
    except Exception as e:
        return f"Error running tests: {str(e)}"


@tool
def create_seed_test() -> str:
    """Create a seed test file for Playwright Test Agents.

    The seed test provides the environment setup and context for the agents.

    Returns:
        str: Success message or error details
    """
    try:
        seed_test_content = """// Seed test for Playwright Test Agents
// This test provides environment setup and context for planner, generator, healer

import { test, expect } from '@playwright/test';

test('seed', async ({ page }) => {
  // This test runs to initialize the environment
  // Add any global setup, project dependencies, and fixtures here
  
  // Example: Navigate to AUT and authenticate
  // await page.goto(process.env.BASE_URL || 'https://example.com');
  
  // This test serves as an example for generated tests
});
"""
        
        seed_file = TECHNICAL_TESTS_DIR / "seed.spec.ts"
        seed_file.parent.mkdir(parents=True, exist_ok=True)
        seed_file.write_text(seed_test_content)
        
        return f"Seed test created at {seed_file}"
    except Exception as e:
        return f"Error creating seed test: {str(e)}"
